---
# TODOs:
# - [ ] add digit width

# loads and trials
loads: [2,4,6]
trials_per_load: 10

# times
# inter - czas odstępu między cyframi
# wait - retention, przetrzymywanie cyfr w umyśle
# response - max czas na odpowiedź
# inter_trial - zakres czasu odstępu między trialami
times:
   fix: [0.5, 0.75]
   digit: 0.15
   inter: 0.35
   wait: [1.5, 2.5]
   response: 1.5
   inter_trial: [0.75, 2]

# keys for yes/no (mapping is randomized)
resp_keys: [f, j]

# fixation cross or circle, units are in degrees
fixation:
   shape: circle
   height: 0.5
   width: 0.1
quit:
   enable: True
   button: q
