
# port and triggers
send_triggers: True
port_adress: '0xCC00'
triggers:
   fix: 11
   digit: [10,1,2,3,4,5,6,7,8,9]
   probe: [20,11,12,13,14,15,16,17,18,19]

# loads and trials
loads: [2,4,6]
trials_per_load: 15
training_trials: 2
fixation_during_wait: True
text_size: 1.5

# times
# inter - czas odstępu między cyframi
# wait - retention, przetrzymywanie cyfr w umyśle
# response - max czas na odpowiedź
# inter_trial - zakres czasu odstępu między trialami
times:
   fix: [0.5, 0.75]
   digit: 0.15
   inter: 0.35
   wait: [1.5, 2.5]
   response: 1.5
   inter_trial: [0.75, 2]

# keys for yes/no (mapping is randomized)
resp_keys: [f, j]

# fixation cross or circle, units are in degrees
fixation:
   shape: circle
   height: 0.5
   width: 0.1
digits:
   height: 5
feedback_circle_radius: 7

break_every_trials: 10
tekst_przerwy: Czas na przerwę - jeżeli masz taką potrzebę.\nMożesz teraz mrugać i ruszać się do woli.\nAby przejść dalej naciśnij dowolny klawisz.

quit:
   enable: True
   button: q
